export const CREATE_MEETING = 'CREATE_MEETING';
export const FETCH_MEETINGS = 'FETCH_MEETINGS';
export const FETCH_MEETING = 'FETCH_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';
export const EDIT_MEETING = 'EDIT_MEETING';
export const ADD_MEETING_POINTS = 'ADD_MEETING_POINTS';
